using TradePro.Api.Providers.IBKR;
using Xunit;

namespace TradePro.Api.Tests.Providers;

/// <summary>
/// IBKR Flex Web Service parsing and error handling.
///
/// WHY THIS INTEGRATION EXISTS. On 1 Oct 2026 the Client Portal positions read
/// was answered from IBKR's cache — "ESNT 118" on every read, all night, while
/// sells filled against it — and a long-only sleeve sold itself to -2,596
/// short. One source said one thing and nothing could contradict it. Flex is
/// generated by IBKR independently of that session, so it can.
///
/// The tests that matter most here are the ones asserting a FAILURE is not
/// read as an empty account. "No positions" and "could not read positions" are
/// the same shape in JSON and opposite in meaning, and the second one being
/// mistaken for the first is how a flatten against an assumed-flat book
/// happens.
/// </summary>
public class IBKRFlexClientTest
{
    // Shapes taken from IBKR's documented Flex output, trimmed to the
    // attributes we read.
    private const string PositionsXml = """
        <FlexQueryResponse queryName="Positions" type="AF">
          <FlexStatements count="1">
            <FlexStatement accountId="DUP656969" fromDate="20261002" toDate="20261002">
              <OpenPositions>
                <OpenPosition accountId="DUP656969" currency="USD" symbol="ESNT"
                  conid="12345" assetCategory="STK" position="-2596"
                  markPrice="60.18" costBasisPrice="63.73"
                  fifoPnlUnrealized="-1303.22" reportDate="20261002" />
                <OpenPosition accountId="DUP656969" currency="USD" symbol="BMRN"
                  conid="67890" assetCategory="STK" position="126"
                  markPrice="59.83" costBasisPrice="60.26"
                  fifoPnlUnrealized="70.98" reportDate="20261002" />
              </OpenPositions>
            </FlexStatement>
          </FlexStatements>
        </FlexQueryResponse>
        """;

    private const string TradesXml = """
        <FlexQueryResponse queryName="Trades" type="AF">
          <FlexStatements count="1">
            <FlexStatement accountId="DUP656969">
              <Trades>
                <Trade accountId="DUP656969" currency="USD" symbol="ESNT"
                  assetCategory="STK" tradeID="777" ibOrderID="888" conid="12345"
                  buySell="SELL" quantity="-118" tradePrice="57.91"
                  proceeds="6833.38" ibCommission="-1.02"
                  dateTime="20261001;064319" />
              </Trades>
            </FlexStatement>
          </FlexStatements>
        </FlexQueryResponse>
        """;

    [Fact]
    public void Positions_parse_including_a_short()
    {
        var rows = IBKRFlexClient.ParsePositions(PositionsXml);
        Assert.Equal(2, rows.Count);

        var esnt = rows.Single(r => r.Symbol == "ESNT");
        // The sign MUST survive. A short read as a long is how the 1 Oct book
        // looked right while being catastrophically wrong.
        Assert.Equal(-2596m, esnt.Quantity);
        Assert.Equal(60.18m, esnt.MarkPrice);
        Assert.Equal(-1303.22m, esnt.UnrealizedPnl);
        Assert.Equal("DUP656969", esnt.Account);
        Assert.Equal(new DateOnly(2026, 10, 2), esnt.ReportDate);

        Assert.Equal(126m, rows.Single(r => r.Symbol == "BMRN").Quantity);
    }

    [Fact]
    public void Trades_parse_with_the_semicolon_datetime_format()
    {
        var rows = IBKRFlexClient.ParseTrades(TradesXml);
        var t = Assert.Single(rows);
        Assert.Equal("ESNT", t.Symbol);
        Assert.Equal("SELL", t.BuySell);
        Assert.Equal(-118m, t.Quantity);
        Assert.Equal(57.91m, t.Price);
        Assert.Equal("888", t.OrderId);
        Assert.NotNull(t.TradeTimeUtc);
        Assert.Equal(new DateTimeOffset(2026, 10, 1, 6, 43, 19, TimeSpan.Zero),
                     t.TradeTimeUtc!.Value);
    }

    [Fact]
    public void A_report_with_no_rows_parses_as_empty_not_as_a_failure()
    {
        const string empty = """
            <FlexQueryResponse queryName="Positions" type="AF">
              <FlexStatements count="1">
                <FlexStatement accountId="DUP656969"><OpenPositions /></FlexStatement>
              </FlexStatements>
            </FlexQueryResponse>
            """;
        Assert.Empty(IBKRFlexClient.ParsePositions(empty));
    }

    // ── error envelopes: Flex answers HTTP 200 with an error BODY ──────

    [Fact]
    public void An_error_body_is_detected_even_though_the_status_was_200()
    {
        const string err = """
            <FlexStatementResponse timestamp="02 October, 2026 09:00 PM EDT">
              <Status>Fail</Status>
              <ErrorCode>1012</ErrorCode>
              <ErrorMessage>Token has expired.</ErrorMessage>
            </FlexStatementResponse>
            """;
        var (code, msg, reference) = IBKRFlexClient.ReadEnvelope(err);
        Assert.Equal("1012", code);
        Assert.Contains("expired", msg);
        Assert.Null(reference);
    }

    [Fact]
    public void A_successful_SendRequest_yields_a_reference_code_and_no_error()
    {
        const string ok = """
            <FlexStatementResponse timestamp="02 October, 2026 09:00 PM EDT">
              <Status>Success</Status>
              <ReferenceCode>1234567890</ReferenceCode>
              <Url>https://ndcdyn.interactivebrokers.com/.../GetStatement</Url>
            </FlexStatementResponse>
            """;
        var (code, _, reference) = IBKRFlexClient.ReadEnvelope(ok);
        Assert.Null(code);
        Assert.Equal("1234567890", reference);
    }

    [Fact]
    public void Generation_in_progress_is_reported_as_its_own_code_not_as_failure()
    {
        // 1019 means "ask again", and conflating it with a real error would
        // make every slow Trades report look broken.
        const string pending = """
            <FlexStatementResponse>
              <Status>Warn</Status>
              <ErrorCode>1019</ErrorCode>
              <ErrorMessage>Statement generation in progress. Please try again shortly.</ErrorMessage>
            </FlexStatementResponse>
            """;
        var (code, _, _) = IBKRFlexClient.ReadEnvelope(pending);
        Assert.Equal("1019", code);
    }

    [Fact]
    public void A_non_xml_body_does_not_throw()
    {
        var (code, _, reference) = IBKRFlexClient.ReadEnvelope("<<not xml at all");
        Assert.Null(code);
        Assert.Null(reference);
    }

    // ── configuration ─────────────────────────────────────────────────

    [Theory]
    [InlineData("", "", "", false)]                  // nothing set
    [InlineData("tok", "", "", false)]               // token but no query — half-configured
    [InlineData("", "111", "222", false)]            // queries but no token
    [InlineData("tok", "111", "", true)]             // positions only is enough
    [InlineData("tok", "", "222", true)]             // trades only is enough
    [InlineData("tok", "111", "222", true)]
    public void Enabled_requires_a_token_AND_at_least_one_query(
        string token, string pos, string trades, bool expected)
    {
        var o = new IBKRFlexOptions
        {
            Token = token, PositionsQueryId = pos, TradesQueryId = trades,
        };
        // A half-configured integration reporting "enabled" is how a silent
        // gap survives — a token with no query id can never return a row.
        Assert.Equal(expected, o.IsEnabled);
    }
}
