namespace TradePro.Api.Providers.IBKR;

/// <summary>
/// IBKR Flex Web Service — scheduled report export.
///
/// WHY THIS EXISTS. Everything else we read from IBKR goes through the Client
/// Portal session, and IBKR grants exactly ONE market-data session per account.
/// Measured 2 Oct 2026 across 285 health probes: only 46% came back healthy,
/// and the dominant failure was "auth VALID but snapshot DARK". Two of the
/// things we lose when that happens are not market data at all:
///
///   * executions — /iserver/account/orders answers `snapshot:false` on 18% of
///     probes, which the probe itself calls "the two-month blindness returning"
///   * positions  — the cached read that sold ESNT twenty-three times on
///     1 Oct 2026 and turned a +118 long into a -2,596 short
///
/// Flex does not touch that session. It is a file, pulled over HTTPS with its
/// own token, generated by IBKR on their side. So it gives us an INDEPENDENT
/// WITNESS for exactly the two things whose single-sourcing has hurt most.
///
/// WHAT IT DELIBERATELY DOES NOT GIVE US. No option chains, no open interest,
/// no greeks, no live quotes. Flex is account activity only. The wheel and
/// strangle data problems are NOT solved here and must not be described as if
/// they were — that would be the "half an idea applied" shape this desk keeps
/// getting bitten by.
///
/// SETUP (manual, once, in IBKR Account Management):
///   Performance &amp; Reports → Flex Queries → Activity Flex Query
///     • one query with the Open Positions section    -> PositionsQueryId
///     • one query with the Trades section            -> TradesQueryId
///     • Format XML, Period "Last N Calendar Days" or "Today"
///   Then Flex Web Service → generate a token        -> Token
/// Store all three in the tradepro/ibkr-flex secret. Nothing turns on until
/// Token plus at least one query id are present.
/// </summary>
public sealed class IBKRFlexOptions
{
    public const string SectionName = "IBKRFlex";

    /// <summary>Flex Web Service token from Account Management. NOT the
    /// OAuth credential used by IBKRClient — a separate secret with a separate
    /// expiry, which is precisely why it survives a dead trading session.</summary>
    public string Token { get; set; } = string.Empty;

    /// <summary>Query id for the Open Positions report.</summary>
    public string PositionsQueryId { get; set; } = string.Empty;

    /// <summary>Query id for the Trades (executions) report.</summary>
    public string TradesQueryId { get; set; } = string.Empty;

    /// <summary>
    /// How long a fetched report stays good. Flex reports are GENERATED on
    /// IBKR's schedule, not on demand — asking again a minute later returns
    /// the same data and burns a request against their rate limit. Ten
    /// minutes is deliberately long: this is a reconciliation witness, not a
    /// quote feed, and anyone wanting "right now" should be reading the
    /// broker session instead.
    /// </summary>
    public int CacheSeconds { get; set; } = 600;

    /// <summary>
    /// Seconds to keep polling GetStatement while IBKR answers "statement
    /// generation in progress" (error 1019). Generation is genuinely slow —
    /// tens of seconds is normal for a trades report.
    /// </summary>
    public int GenerationTimeoutSeconds { get; set; } = 120;

    /// <summary>Base URL. Overridable only so tests can point at a stub.</summary>
    public string BaseUrl { get; set; } =
        "https://ndcdyn.interactivebrokers.com/AccountManagement/FlexWebService";

    /// <summary>Enabled when a token and at least one query id are configured.
    /// There is no separate on/off flag: a half-configured integration that
    /// reports "enabled" is how a silent gap survives.</summary>
    public bool IsEnabled =>
        !string.IsNullOrWhiteSpace(Token)
        && (!string.IsNullOrWhiteSpace(PositionsQueryId)
            || !string.IsNullOrWhiteSpace(TradesQueryId));
}
