using TradePro.Api.Providers.IBKR;

namespace TradePro.Api.Endpoints;

/// <summary>
/// IBKR Flex Web Service — positions and executions as a scheduled report,
/// independent of the Client Portal market-data session.
///
/// WHY A SEPARATE FILE. The archive endpoints were once registered onto the
/// wrong group because two groups lived in one file and the variable was
/// called `group` in both. These live on their own so the group they attach
/// to is unambiguous.
///
/// Routes are mounted under the same /api prefix as the other integrations:
///   GET /api/integrations/ibkr/flex/status
///   GET /api/integrations/ibkr/flex/positions
///   GET /api/integrations/ibkr/flex/trades
///   GET /api/integrations/ibkr/flex/reconcile   <- the point of all this
/// </summary>
public static class IBKRFlexEndpoints
{
    public static IEndpointRouteBuilder MapIBKRFlexEndpoints(this IEndpointRouteBuilder app)
    {
        // Is it configured, and what would it answer for? Deliberately says
        // WHICH half is missing: a token with no query ids is a different
        // problem from no token, and "disabled" hides both.
        app.MapGet("/integrations/ibkr/flex/status", (IBKRFlexClient flex) =>
            Results.Ok(new
            {
                enabled = flex.IsEnabled,
                positionsQueryId = flex.PositionsQueryId,
                tradesQueryId = flex.TradesQueryId,
                note = flex.IsEnabled
                    ? "Flex reads account activity only — positions and executions. "
                    + "It carries NO option chains, open interest or quotes, and does "
                    + "not fix the market-data session."
                    : "Not configured. Set IBKRFlex:Token plus at least one of "
                    + "IBKRFlex:PositionsQueryId / IBKRFlex:TradesQueryId in the "
                    + "tradepro/ibkr-flex secret. See IBKRFlexOptions for the "
                    + "Account Management steps.",
            }))
            .WithName("IBKRFlexStatus");

        app.MapGet("/integrations/ibkr/flex/positions",
            async (IBKRFlexClient flex, CancellationToken ct, bool fresh = false) =>
            {
                var r = await flex.GetPositionsAsync(ct, forceFresh: fresh);
                return Results.Ok(new
                {
                    enabled = r.Enabled, error = r.Error, fetchedAtUtc = r.FetchedAtUtc,
                    fromCache = r.FromCache, queryId = r.QueryId,
                    count = r.Rows.Count, positions = r.Rows,
                });
            })
            .WithName("IBKRFlexPositions");

        app.MapGet("/integrations/ibkr/flex/trades",
            async (IBKRFlexClient flex, CancellationToken ct, bool fresh = false) =>
            {
                var r = await flex.GetTradesAsync(ct, forceFresh: fresh);
                return Results.Ok(new
                {
                    enabled = r.Enabled, error = r.Error, fetchedAtUtc = r.FetchedAtUtc,
                    fromCache = r.FromCache, queryId = r.QueryId,
                    count = r.Rows.Count, trades = r.Rows,
                });
            })
            .WithName("IBKRFlexTrades");

        // THE REASON THIS INTEGRATION EXISTS.
        //
        // On 1 Oct 2026 the Client Portal positions read was answered from
        // IBKR's cache — "ESNT 118" on every read, all night, while sells
        // filled against it. A long-only sleeve sold itself to -2,596 short
        // because one source said one thing and nothing else could contradict
        // it. Flex is generated by IBKR independently of that session, so it
        // can.
        //
        // Disagreement here is INFORMATION, not an error: Flex is a periodic
        // snapshot and the session read is live, so they legitimately differ
        // intraday. What must never happen again is the two differing by a
        // whole position while nothing notices.
        app.MapGet("/integrations/ibkr/flex/reconcile",
            async (IBKRFlexClient flex, IBKRClient ibkr, CancellationToken ct) =>
            {
                if (!flex.IsEnabled)
                    return Results.Ok(new
                    {
                        enabled = false,
                        note = "Flex not configured — no second witness available. "
                             + "The session read is currently single-sourced.",
                    });

                var f = await flex.GetPositionsAsync(ct);
                if (f.Error is not null)
                    return Results.Ok(new { enabled = true, error = f.Error });

                var live = await ibkr.GetPositionsAsync(ct, forceFresh: true);
                if (live.Error is not null)
                    return Results.Ok(new
                    {
                        enabled = true,
                        error = $"Flex read fine ({f.Rows.Count} rows) but the broker "
                              + $"session did not: {live.Error}. That asymmetry is itself "
                              + "the finding — Flex survives a dead market-data session.",
                        flexCount = f.Rows.Count,
                    });

                var flexBy = f.Rows
                    .GroupBy(p => p.Symbol.ToUpperInvariant())
                    .ToDictionary(g => g.Key, g => g.Sum(x => x.Quantity));
                var liveBy = live.Positions
                    .Where(p => p.Quantity != 0)
                    .GroupBy(p => (p.Symbol ?? "").ToUpperInvariant())
                    .ToDictionary(g => g.Key, g => g.Sum(x => x.Quantity));

                var all = flexBy.Keys.Union(liveBy.Keys).OrderBy(x => x);
                var diffs = new List<object>();
                foreach (var sym in all)
                {
                    flexBy.TryGetValue(sym, out var fq);
                    liveBy.TryGetValue(sym, out var lq);
                    if (fq != lq)
                        diffs.Add(new { symbol = sym, flex = fq, session = lq, delta = lq - fq });
                }

                return Results.Ok(new
                {
                    enabled = true,
                    flexAsOfUtc = f.FetchedAtUtc,
                    flexCount = flexBy.Count,
                    sessionCount = liveBy.Count,
                    agree = diffs.Count == 0,
                    disagreements = diffs,
                    note = "Flex is a periodic report and the session read is live, so "
                         + "intraday differences are expected and are not an error. A "
                         + "whole position appearing on one side only is the thing worth "
                         + "acting on.",
                });
            })
            .WithName("IBKRFlexReconcile");

        return app;
    }
}
